id = "objectscript"
name = "InterSystems ObjectScript"
version = "1.0.1"
schema_version = 1
authors = ["Dave McCaldon <davem@intersystems.com>"]
description = "InterSystems IRIS ObjectScript Extension"
repository = "https://github.com/intersystems/zed-objectscript"

[grammars.objectscript_udl]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
commit = "320a28654593428e5a7da76b034ce9d5a1cc528a"
path = "udl"
